add: ultramarine-system-configs
Ultramarine-Linux/ultramarine-pkgs pull request #37
Opened 2024-08-03 05:13 UTC by korewaChino

Adds a new system-configs package which contains all the major system tweaks, also moves the networking tweaks from ultramarine-release to this package.

The configs do the following:
- Compress systemd journal and limit size to 200M
- systemd-tmpfiles config to automatically clean up /tmp and /var/tmp
- logrotate config to rotate log files and compress them daily, with weekly backlog rotation
- Enable the `tcp_bbr` kernel module by Google and enable BBR congestion control as a sysctl knob
- Enables TCP Fast Open to reduce networking latency
- MTU Probing moved from ultramarine-release

2024-08-03 05:41 UTC, lleyton requested changes
hm, looks good so far, but I'd love to see benchmarks/QA

additionally, we shouldn't land these for 40, but 41

also, maybe we should break this into both core and desktop defaults packages

2024-08-03 10:40 UTC, korewaChino commented
> hm, looks good so far, but I'd love to see benchmarks/QA

For BBR, this should be enough I think https://medium.com/google-cloud/tcp-bbr-magic-dust-for-network-performance-57a5f1ccf437, Hopefully BBRv2 or v3 has improved network quality in cases of flaky networking conditions though, According to APNIC BBRv1 may not be beneficial over the standard Cubic implementation when you have lots of packet loss in a flaky networking environment since BBR considers that congestion instead of just the network itself being lossy

Actually, for TFO I'm starting to reconsider it now that it allows for tracking users (since it uses cookies)...
 
More testing and data needed.

The FS cleanup configs should good to go though, I have moved them to the desktop subpackage specifically so we can simply just add them to the comps list and have the networking/core perf configs optional

2024-08-03 10:42 UTC, korewaChino commented
Should I make subpackages by type of tweaks or should I go with a `core` and a `desktop` subpackage?

2024-08-03 10:46 UTC, korewaChino commented
And for MTU probing, it has already been added since UM40, and this fixes some applications that transmit really big packets (i.e modded Minecraft clients/servers, Ubisoft Connect authentication). Fixes basically all Ubisoft Connect games, I tested with UNO specifically but should apply for other games that use it too.

2024-09-19 22:46 UTC, lleyton requested changes

2024-09-19 22:46 UTC, lleyton commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
what is the rationale for cake?

2024-09-19 22:46 UTC, lleyton commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.ipv4.tcp_fastopen=3
I don't think we should do this, there are privacy concerns that have yet to be solved AFAIK.

2024-09-19 22:46 UTC, lleyton commented on ultramarine/ultramarine-system-configs/journal-cleanup.conf
> +Compress=yes
Compress is already defaulted and SystemMaxUse is a sane percentage of the system already.

2024-09-19 22:46 UTC, lleyton commented on ultramarine/ultramarine-system-configs/ultramarine-logrotate.conf
> +rotate 1
maybe 3 weeks, 1 week feels a bit low?

2024-09-19 22:46 UTC, lleyton commented on ultramarine/ultramarine-system-configs/tmpfiles-cleanup.conf
> +D! /tmp 1777 root root 0
I thought systemd already did these?

2024-09-19 23:51 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.ipv4.tcp_fastopen=3
Yeah cookies are weird

2024-09-19 23:53 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
https://wiki.archlinux.org/title/Sysctl#Enable_BBR

2024-09-20 00:14 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
Also, https://www.bufferbloat.net/projects/codel/wiki/Cake/

CAKE is a queue management algorithm based on htb and fq_codel with many improved features at a small CPU cost, which is negligible for modern hardware

2024-10-07 04:30 UTC, lleyton requested changes, later dismissed

2024-10-07 04:30 UTC, lleyton commented on comps.xml
> +      <packagereq type="default">dnf5-default-package-manager</packagereq>
```suggestion
```

2024-10-07 04:30 UTC, lleyton commented on ultramarine/ultramarine-system-configs/tmpfiles-cleanup.conf
> +# remove files in /var/tmp older than 10 days
I want to say the upstream default is 30d, which I think is good enough for /var/tmp, and for /tmp it's 10d (albeit, that's backed by memory)

is it really a good idea to lower it? considering /var/tmp is for temporary files that should live longer than /tmp (from my understanding)

2024-10-07 04:30 UTC, lleyton commented on ultramarine/ultramarine-system-configs/tmpfiles-cleanup.conf
> +# namespace mountpoints (PrivateTmp=yes) are excluded from removal
I thought these were set in upstream configs?

2024-10-07 04:30 UTC, lleyton commented on ultramarine/ultramarine-system-configs/ultramarine-logrotate.conf
> +compress
uncomment this...?

2024-10-07 04:30 UTC, lleyton commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.ipv4.conf.all.rp_filter = 1
why default and all?

2024-10-07 04:30 UTC, lleyton commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
why did you remove cake?

2024-10-07 08:04 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/ultramarine-logrotate.conf
> +compress
copied from archwiki

2024-10-07 08:06 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.ipv4.conf.all.rp_filter = 1
so it disables them all and future connections

2024-10-07 08:09 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
https://github.com/Ultramarine-Linux/packages/pull/37#discussion_r1760567510 I assumed you didn't want it

2024-10-07 08:16 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/tmpfiles-cleanup.conf
> +# remove files in /var/tmp older than 10 days
I feel like it still takes too much space for a desktop-oriented distro, since desktop apps are very noisy in logs (I see you Steam)

2024-10-07 08:36 UTC, korewaChino commented on ultramarine/ultramarine-system-configs/networking-tweaks.conf
> +net.core.default_qdisc = cake
I added it back. Do we *actually* want it or not?

2024-10-07 10:44 UTC, korewaChino commented
Here's networking benchmark results for the sysctl flags
![image](https://github.com/user-attachments/assets/b4fc0cb6-0f0c-4418-b150-be513c004e5c)

2024-10-07 11:10 UTC, korewaChino commented
Going for BBR + Cake here since it's the most balanced one out of all of them, leads to slightly better QoS

2024-10-07 13:24 UTC, madonuko approved these changes

2024-10-07 13:27 UTC, merged