feat(shell-config): add neofetch message
Ultramarine-Linux/ultramarine-pkgs pull request #38
Opened 2024-08-04 13:00 UTC by madonuko

2024-08-04 15:11 UTC, nothingneko approved these changes, later dismissed

2024-08-04 15:11 UTC, nothingneko commented on ultramarine/shell-config/ultramarine-shell.sh
> +        echo 'neofetch is not installed.'
```suggestion
        echo 'Neofetch is not installed.'
```

2024-08-04 15:11 UTC, nothingneko commented on ultramarine/shell-config/ultramarine-shell.sh
> +        echo 'While it is available via `sudo dnf in neofetch`, it does not come with the Ultramarine logo.'
```suggestion
        echo 'While neofetch is available in Ultramarine, it does not come with our logo, and is no longer maintained.'
```

2024-08-04 15:11 UTC, nothingneko commented on ultramarine/shell-config/ultramarine-shell.sh
> +        echo 'We recommend fastfetch instead, which may be installed via:'
```suggestion
        echo 'We recommend fastfetch instead, which may be installed using:'
```

2024-08-04 15:11 UTC, nothingneko commented on ultramarine/shell-config/ultramarine-shell.sh
> +        echo '  sudo dnf in fastfetch'
```suggestion
        echo '  sudo dnf install fastfetch'
```
(for consistency with docs)

2024-08-18 20:29 UTC, lleyton requested changes

2024-08-18 20:29 UTC, lleyton commented on ultramarine/shell-config/ultramarine-shell.sh
> +        echo 'You may disable this message by installing hyfetch-neofetch or neofetch.'
neofetch is deprecated upstream

2024-08-19 13:23 UTC, lleyton approved these changes

2024-08-19 13:26 UTC, merged