feat: add fastfetch and include in comps; update hyfetch
Ultramarine-Linux/ultramarine-pkgs pull request #54
Opened 2024-08-19 07:20 UTC by madonuko

I was about to obsolete `hyfetch` but I kinda realized we never updated it… so maybe we should try out this newer version

I also included `fastfetch` in comps so desktop users don't have to install it… I mean it's kinda bloaty but it's just 2.5 MiB… not sure

2024-08-26 02:04 UTC, lleyton commented
you probably want to pull um41 into your branch and resolve conflicts, I'm pretty sure I already added fastfetch into one of my PRs

2024-08-26 08:09 UTC, lleyton requested changes

2024-08-26 08:09 UTC, lleyton commented on ultramarine/hyfetch/hyfetch.spec
> +/usr/lib/python*/site-packages/HyFetch-%version-py*.egg/
macro?

2024-08-26 08:09 UTC, lleyton commented on comps.xml
> +      <packagereq type="default">fastfetch</packagereq>
already in ultramarine-product-common?

2024-09-05 23:59 UTC, lleyton commented
Please fix the failing build

2024-09-06 08:38 UTC, madonuko commented
I think gha is broken

2024-09-06 20:05 UTC, lleyton commented
uh, wtf...

2024-09-06 20:06 UTC, lleyton approved these changes

2024-09-06 20:06 UTC, merged

2024-09-06 20:11 UTC, lleyton commented
merged it because thought it might get GHA to actually work, seems like build still failing, can you look at it?