switch to slick-greeter
Ultramarine-Linux/ultramarine-pkgs pull request #99
Opened 2024-11-25 05:14 UTC by nothingneko

2024-11-25 19:46 UTC, lleyton requested changes
you still need to modify 60-ultramarine-presets.conf, also, just adding the config files don't add them to the package, you need to modify the spec

there's no use to keeping around gtk greeter configs too imo

2024-11-25 20:04 UTC, nothingneko commented
> you still need to modify 60-ultramarine-presets.conf, also, just adding the config files don't add them to the package, you need to modify the spec
> 
> 
sorry i was sleepy
> there's no use to keeping around gtk greeter configs too imo
i think we should just for one release

2024-11-25 20:09 UTC, lleyton commented
> i think we should just for one release
I would agree, but the issue is both configs would conflict in the current state (they seem to apply regardless of greeter)

2024-11-26 08:17 UTC, lleyton approved these changes

2024-11-26 08:17 UTC, merged